### ISSUE TITLE
make error for hydro ubuntu 12.04 

### ISSUE THREAD

**Issue by aaravrav142** [koenlek/ros_lemtomap#1]
Hi, 

I am having the following errors when doing catkin_make. System info- Ros hydro, ubuntu 12.04 LTS. 

Scanning dependencies of target move_base_topo
[ 85%] Building CXX object lemtomap_meta/lemto_navigation/CMakeFiles/move_base_topo.dir/src/move_base_topo.cpp.o
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp: In member function ‘void StMapLoader::loadYAML()’:
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:53:20: error: ‘LoadFile’ is not a member of ‘YAML’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:55:48: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:55:51: error: expected primary-expression before ‘int’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:55:51: error: expected ‘;’ before ‘int’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp: In function ‘void operator>>(const YAML::Node&, geometry_msgs::Pose&)’:
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:65:50: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:65:53: error: expected primary-expression before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:65:53: error: expected ‘;’ before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:66:50: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:66:53: error: expected primary-expression before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:66:53: error: expected ‘;’ before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:67:50: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:67:53: error: expected primary-expression before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:67:53: error: expected ‘;’ before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:68:56: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:68:59: error: expected primary-expression before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:68:59: error: expected ‘;’ before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:69:56: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:69:59: error: expected primary-expression before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:69:59: error: expected ‘;’ before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:70:56: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:70:59: error: expected primary-expression before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:70:59: error: expected ‘;’ before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:71:56: error: ‘const class YAML::Node’ has no member named ‘as’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:71:59: error: expected primary-expression before ‘double’
/home/rd/catkin_ws/src/lemtomap_meta/lemto_topological_mapping/src/load_map.cpp:71:59: error: expected ‘;’ before ‘double’
make[2]: **\* [lemtomap_meta/lemto_topological_mapping/CMakeFiles/topological_navigation_mapper.dir/src/load_map.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....

Can you suggest me how do I resolve this issue.

Thanks

Alex

**Comment by koenlek** [comment]
Hi Alex,

The release is taylored for Indigo on 14.04, so it won't run anymore on Hydro. You can try to make it work with hydro again. Any hinst for that can be found by comparing the latests hydro commit and the first indigo commit (`git diff 154c78..c0a1da`). 

A quick scan reminds me that the main changes are:
- For hydro compatibility, comment the cmake_modules in the CMakeLists.txt again...

That should actually be it. Also, clearly it is having issues finding yaml-cpp. I recall I switched from yaml-cpp 0.3.x to 0.5.x at some point, and that 0.5.x syntax was not backward compatible with 0.3.x syntax. Make sure to install libyaml-cpp packages from apt (both 0.5 and 0.3 if possible, and the -dev packages). I am not sure if you can run 0.5 on 12.04, so maybe you need to convert to 0.3 syntax... Good luck!

**Comment by aaravrav142** [comment]
Thanks, yaml-cpp is still giving problems. I swtiched to Indigo and its working fine under indigo.  I will try to find out solution for the Hydro. When will the release for actual robot be released. I am interested in developing the semantic mapping package for external robot use. So far I believe lemtomap requires perfect odometry and is only simulation based. BTW, excellent work. I am reading your thesis work and its great. Keep up the good work. 

Regards
Alex

**Comment by koenlek** [comment]
Hi Alex, 

Good to hear that someone is enjoying my thesis! Unfortunately, I have stopped working on lemtomap for now (I graduated and started a job at a robotics company, but there we do not need something like lemtomap at this point). I really think there is a nice potential in the system described in my thesis, but within the scope of my thesis I unfortunately could only get a small part of the implementation done. Moreover, it was my first real ROS/c++ experience... If you are interested in progressing the implementation, please let me know!

Btw, did you manage to solve the problems by now? 

Best,
Koen

**Comment by aaravrav142** [comment]
Hi Koen,

I am now in the process to implement your project on a Pioneer P3DX robot with a laser scanner. It is working good in the simulations, however not so good in the actual robot. Nevertheless, its a cool project. I haven't found the solution for the Hydro yet. If possible can you create a Hydro-devel branch for the code if you have time.Also good luck to you with the job. I hope you can continue to develop Lemento map in your spare time. 

Regards
Alex

**Comment by koenlek** [comment]
Hi Alex,

If you want you can create a fork of it to you own github, then in your own account make a hydro-devel branch in which you apply your changes that make it Hydro compatible. If you think it works fine, create a pull request (from my lemtomap github page) to request merging your forked branch into my repository. 

Good luck!
Koen
