### ISSUE TITLE
Is this project an indigo version of topological_navigation?

### ISSUE THREAD

**Issue by histfuture** [koenlek/ros_lemtomap#2]

**Comment by koenlek** [comment]
No, it is not. Although my work was inspired by it, it is an independent implementation of a similar concept. My thesis itself can be found here: http://repository.tudelft.nl/islandora/object/uuid:8973addb-9253-4a78-a3d9-6aa58789b90f?collection=education

The "topological_navigation" that you're referring to was actually developed for ROS Diamondback (which is really old ;)). For my research, I ported that version to ROS Fuerte https://github.com/koenlek/topological_navigation_fuerte which you could run in e.g. a Docker (I found this one: https://hub.docker.com/r/fabian/ubuntu-12.04-ros-fuerte/) based environment or an Ubuntu 12.04 virtual machine. To further migrate it to Indigo or Kinetic would be quite some work I think (migrating to catkin)
